---
title: "Practice raster manipulations"
format: html
editor: visual
---

## 1. Get Started 

```{r}
library(tidyverse)
library(spData)
library(spDataLarge)
library(sf)
library(stars)
library(terra)
```

```{r}
# Digital elevation model (DEM) of Mt Mongon 

dem <- terra::rast(system.file("raster/dem.tif", package = "spDataLarge"))

# Landsat image of Zion NP

landsat <- terra::rast(system.file("raster/landsat.tif", package = "spDataLarge"))

# SRTM elevation of Zion NP

srtm <- terra::rast(system.file("raster/srtm.tif", package = "spDataLarge"))
```

## 2. Explore elevation at Mt. Mongon, Peru

```{r}
boxplot(dem, 
        main = "Digital Elevation Model (DEM)", 
        ylab = "Meters")

hist(dem, 
     main = "Digital Elevation Model (DEM)", 
     ylab = "Frequency", 
     xlab = 'Value')
```

```{r}
# Reclassify dem and compute mean for three classes 

rcl <- matrix(c(-Inf, 300, 0, 
                300, 500, 1, 
                500, Inf, 2), 
              ncol = 3, byrow = TRUE)

# Apply the matrix to reclassify the raster, making all cells 0, 1, or 2 

dem_rcl <- terra::classify(dem, rcl = rcl)


# Assign labels to the numerical categories 

levels(dem_rcl) <- tibble::tibble(id = 0:2, 
                                  cats= c("low", "medium", "high"))

# Calculate mean elevation for each category using original DEM values 

elevation_mean <- terra::zonal(dem, dem_rcl, fun = "mean")
elevation_mean

```

## 3. Explore NDVI and NDWI at Zion National Park

```{r}
scale_factor <- 0.0000275
offset <- 0.2

scale_function <- function(x) {
  x * scale_factor + offset
}

landsat_scaled <- terra::app(landsat, fun = scale_function)
```

```{r}
ndwi_fun <- function(green, nir){
  (green - nir)/(green + nir)
}

ndvi_fun <- function(nir, red){
  (nir - red)/(nir + red)
}
```

```{r}
ndwi_rast <- terra::lapp(landsat_scaled[[c(2, 4)]],
                         fun = ndwi_fun)

ndvi_rast <- terra::lapp(landsat_scaled[[c(4, 3)]],
                         fun = ndvi_fun)
```

```{r}
plot(ndwi_rast, 
     main = "Zion National Park NDWI")
```
```{r}
plot(ndvi_rast, 
     main = "Zion National Park NDVI")
```
```{r}

combine <- c(ndvi_rast, ndwi_rast) # Stack rasters 
plot(combine, main = c("NDVI", "NDWI"))

```
```{r}
# Calculate the correlation between raster layers 

terra::layerCor(combine, fun = cor)
```

## 4. Change the resolution of elevation at Zion NP

```{r}
plot(srtm)
```

