---
title: "Week 3: Discussion Section"
format: html
editor: visual
---

## 1. Get Started 

```{r}
library(here)
library(tidyverse)
library(sf)
library(tmap)
```

```{r}
sb_protected_areas <- st_read(here("data", "week3",  "cpad_super_units_sb.shp"))|>  
  st_transform("ESRI:102009")

sb_city_boundaries <- st_read(here("data", "week3",  "sb_city_boundaries_2003.shp")) |> 
  st_transform("ESRI:102009")

sb_county_boundary <- st_read(here("data", "week3",  "sb_county_boundary_2020.shp")) |> 
  st_transform("ESRI:102009")

aves <- st_read(here("data", "week3",  "aves_observations_2020_2024.shp")) |> 
  st_transform("ESRI:102009")
```

## 2. Find bird observations within PAs in Santa Barbara County

```{r}
# Subset 
aves_PA_subset <- sb_protected_areas[aves, ]

# Check number of rows 
nrow(aves_PA_subset)

```

```{r}
# Spatial subset plot 

tm_shape(sb_protected_areas) + 
  tm_fill() + 
  tm_shape(sb_protected_areas) + 
    tm_borders(lwd = 1, col = "dodgerblue") + 
    tm_fill(col = "dodgerblue", alpha = 0.2) +     tm_shape(aves_PA_subset) + 
  tm_dots(size = .09)

```

```{r}
# Spatial join 
# Default: `st_intersects`
aves_PA_join <- st_join(aves, sb_protected_areas) 
nrow(aves_PA_join)

```

```{r}

# Plot spatial join 

tm_shape(sb_county_boundary) + 
  tm_fill() + 
  tm_shape(sb_protected_areas) + 
  tm_fill(col = "dodgerblue", alpha = 0.2) + 
  tm_shape(aves_PA_join) + 
  tm_dots(col = "darkblue", size = .09)

```
```{r}
# Make a 5km buffer around the protected areas and subset buffered geometries to only those with bird observations

# Check if units are in meters
st_crs(sb_protected_areas)$units

# Create a 5000m buffer zone
PA_buffer_5km <- st_buffer(sb_protected_areas, dist = 5000)

# Subset 
aves_buffer_subset <- PA_buffer_5km[aves, ]

```
```{r}

tm_shape(sb_county_boundary) + 
  tm_fill() + 
  tm_shape(sb_protected_areas) + 
  tm_borders() + 
  tm_fill(col = "dodgerblue", alpha = 0.2) + 
  tm_shape(aves_buffer_subset) + 
  tm_dots(col = "darkblue", size = 0.09)
  
```
## 3. Find PAs within 15km of Goleta 

```{r}
# Subset SB county to Goleta 

goleta <- sb_city_boundaries |> 
  dplyr:: filter(NAME == "Goleta") 

# Check if units are in meters 
st_crs(goleta)$units 
```
```{r}
# Create a 15 km buffer around goleta 

goleta_buffer_15km <- st_buffer(goleta, dist = 15000)
```

```{r}
# Explore different outputs for #3 with st_intersects(), st_intersection(), st_within()


```


